### PR TITLE
Add @

### PR DESCRIPTION
**Pull request by flexbox**
Closes issue #85

### CODE REVIEW

**Comment by wesbos** [comment]
Can you reorder it so 64 comes after 63?

**Comment by flexbox** [comment]
Hummm i don't know what you are talking about (no `git undo` && `git push -f` used 😄 )

**Comment by flexbox** [comment]
Fix done !

**Comment by wesbos** [comment]
Thanks- does this only fire in Firefox?

**Comment by flexbox** [comment]
In firefox 

- 64

In safari, Chrome, Opera

- 192

Tested on macOS

**Pull request merged**
