### PR TITLE
"Missing" key code 168

### PR DESCRIPTION
**Pull request by chiizi**
On Chrome OS, Ctrl+Refresh fires this event. This is pretty specific and obscure though, so I don't know if this should be added.

### CODE REVIEW

**Comment by wesbos** [comment]
Does either key fire it as well?

**Comment by thomasmorelli** [comment]
This PR has an error. @chiizi There should be a comma after `"ctrl + refresh (Chromebook)"`

**Comment by chiizi** [comment]
Thanks for noticing that.

**Comment by chiizi** [comment]
It only happens when holding Ctrl, Shift, Alt, or the Search key. Also, the power button behaves similarly and fires 152.

**Comment by wesbos** [comment]
Ah could you rebase this? Or just open another PR?

**Pull request closed without merging**
