### PR TITLE
Adding SHIFT pressed keys

### PR DESCRIPTION
**Pull request by daniloprates**
I've added the ability to see keys with `shift` and `alt` pressed.
The idea is to create an array for the `shift` keys and another for the `alt` keys.
To get the specific code it needs for use `onkeypress`, instead of `onkeydown`.

Please feel free to ignore it or use some parts of it.

Thanks the project. Quite useful.

Cheers,
Danilo

### CODE REVIEW

**Comment by wesbos** [comment]
Thanks a ton - do you know how this works with international keyboards? I would imagine it's a nightmare of combos but  would like to add it

**Comment by daniloprates** [comment]
Hey, I'm very glad you liked it. I've done it on a Brazilian keyboard, with latin accents and it worked fine. Maybe it's worth asking @LayZeeDK, who's done the Danish accent, to test as well.

**Comment by daniloprates** [comment]
Just realised after rebasing it stopped working. Maybe encoding issues. I've pushed the correction.

**Comment by sevillaarvin** [comment]
Any chance this will get added?

**Comment by LayZeeDK** [comment]
Alt and Shift combinations are already detected (also works with Danish letters). This can be closed.

**Pull request closed without merging**
