### PR TITLE
All letters will have same width

### PR DESCRIPTION
**Pull request by BlueManCZ**

### CODE REVIEW

**Comment by palashmon** [comment]
Hi, thanks for your contribution.

Could you please share some screenshots for what it looked like before and after your changes?
 
Regards!

**Comment by BlueManCZ** [comment]
Of course.

**Before** (different widths):
screenshot_20180618_173746
**After** (same widths for all letters)
screenshot_20180618_173850

Hope this helped.

**Comment by palashmon** [comment]
Yup, I tested it. This looks awesome, but I think `min-width: 24px;` is the perfect one. There is still small width change if we have 23px width. Could you please check that once and update the code accordingly.

Regards!

**Comment by BlueManCZ** [comment]
I'm using Firefox and 23 is fine there. But right, in Webkit there is a small change. `min-width: 24px;` is optimal for both.

**Comment by palashmon** [comment]
Awesome! Thanks!

**Pull request merged**
