### PR TITLE
[DONE] No more jQuery

### PR DESCRIPTION
**Pull request by jhonnymoreira**
# To Do

- [x] Update the `scripts.js` file
- [x] Update the `index.html` file

### CODE REVIEW

**Comment by wesbos** [comment]
Nice! Been meaning to do this. Thanks :)

**Comment by fearphage** [comment]
You're missing analytics from browsers that don't support `doc.querySelector` now. They never make it to the GA include. You should shift the Google analytics before the non-universally supported calls so you can track who's not getting to use the page. That's just a thought.

**Comment by wesbos** [comment]
document.querySelector is IE8+  I highly doubt there are any devs using IE7 - and if they are, I don't want to know about it :)

**Comment by fearphage** [comment]
Fair enough. :+1:

**Comment by jhonnymoreira** [comment]
Glad I was able to help [=

**Pull request merged**
