### PR TITLE
Fix code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
Hi :wave: 
This pull request fixes some of the code quality issues raised by DeepSource on my fork of this repository.
I have already fixed some issues using DeepSource's Autofix.

Take a quick look at all the issues caught by DeepSource for this repository [here](https://deepsource.io/gh/withshubh/keycodes/issues/?category=recommended)

### Summary of fixes

- Format code with prettier
- Added .`deepsource.toml`

You can also have a look at the [configuration file](https://github.com/withshubh/keycodes/blob/gh-pages/.deepsource.toml) I used for DeepSource Analysis.

### Using DeepSource to continuously analyze your repository

- Merge this PR. I have included a `.deepsource.toml` in this PR, which you can use to configure your analysis settings.
- Install DeepSource on your repository [here](https://deepsource.io/signup).
- Activate analysis [here](https://deepsource.io/gh/wesbos/keycodes/).

### CODE REVIEW

**Comment by wesbos** [comment]
hey thanks a ton, but these just seem like formatting issues, going to keep it as-is

**Comment by withshubh** [comment]
Hey :wave:  @wesbos Did you check [DeepSource](https://deepsource.io/)?

Integrating DeepSource on your repository will automate code reviews. 
I'd suggest you try it since DeepSource is and will always be free for Open Source projects.

**Comment by wesbos** [comment]
thanks - will check out deep source for sure! This repo needs to stay simple though

**Comment by withshubh** [comment]
> thanks - will check out deep source for sure! This repo needs to stay simple though

Thanks @wesbos :sparkling_heart: 
If you have any questions regarding [DeepSource](https://deepsource.io/) I'll be happy to answer.

**Pull request closed without merging**
