### PR TITLE
Added the presumed missing function keys F26-F32

### PR DESCRIPTION
**Pull request by PeterCyrus**
This change enables a 20-key auxiliary keyboard to return keycodes that are not produced by a normal keyboard, so it can be used to input new letters, not just duplicates of existing letters.

### CODE REVIEW

**Comment by wesbos** [comment]
thanks a ton!

**Comment by PeterCyrus** [comment]
I just joined GitHub (to do this), so I had no idea how it works.

What is the relationship between the github code and the site keycode.info?

**Comment by wesbos** [comment]
The site is hosted straight from github on something called github pages, so it should be live already :)

**Comment by PeterCyrus** [comment]
:( Then my keyboard isn't working.

**Comment by PeterCyrus** [comment]
My physical keyboard is working, and even the hack I installed to get it to
produce these extra keycodes is probably working.   But the OS or the
browser is not passing them to the keycode.info JS code.

I'll try reading them with Java, in case it's the browser.

Anyway, thanks for your help.  I hope those extra codes are useful to
someone.

**Comment by wesbos** [comment]
okay let me know - there might be a cached version.

**Pull request merged**
