### PR TITLE
Show 'Space' instead of ' ' for e.key when the spacebar is pressed

### PR DESCRIPTION
**Pull request by jasonlbeggs**
This PR just fixes the small issue mentioned in #239.

### CODE REVIEW

**Comment by jasonlbeggs** [comment]
We can do that, but it makes that box taller than the others. 
screen shot 2018-10-03 at 8 30 27 am

What if we do something like this?
screen shot 2018-10-03 at 8 32 53 am

**Comment by palashmon** [comment]
Second option with just text `(Space character)` looks great. :+1:

**Comment by jasonlbeggs** [comment]
Changes pushed!

**Comment by palashmon** [comment]
Awesome. Thanks for this PR!

**Pull request merged**
